Implement Hilt
naufalprakoso/Bill-Reminder pull request #1
Opened 2020-10-04 06:04 UTC by AntoniKwok

2020-10-04 11:39 UTC, naufalprakoso requested changes
Thanks for your contribution 🎉. After I test and checked it, I found an issue. After adding a new bill data, the bills did not show in the Bills Unpaid and Bills page.

2020-10-04 11:39 UTC, naufalprakoso commented on app/build.gradle
>  }
Hilt uses Java 8 features, better to enable Java 8 in this project:
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

2020-10-04 11:39 UTC, naufalprakoso commented on app/build.gradle
> +
Nit: Please add
`// Hilt`

2020-10-04 11:39 UTC, naufalprakoso commented on app/src/main/java/com/naufalprakoso/billreminder/ui/bill/detail/BillDetailActivity.kt
> +import java.util.*
Better to not use wildcard import in here

2020-10-04 11:39 UTC, naufalprakoso commented on app/src/main/java/com/naufalprakoso/billreminder/ui/main/all/BillAdapter.kt
> +import java.util.*
Better to not use wildcard import in here

2020-10-06 14:40 UTC, AntoniKwok commented
Hi @naufalprakoso , Thank you for your feedback and comment

2020-10-06 15:04 UTC, naufalprakoso approved these changes
Thanks for your great contribution 🔥

2020-10-06 15:04 UTC, naufalprakoso commented on app/src/main/java/com/naufalprakoso/billreminder/utils/DiffUtilCallback.kt
> +class DiffUtilCallback(
Nice 🎉

2020-10-06 15:04 UTC, merged